version: "3.4"
services:
  web:
    build: .
    command: yarn dev
    restart: always
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/crawler
    networks:
      - backend
  redis:
    image: redis:6.0.1-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend   
networks:
  backend:
    driver: bridge