version: "3.4"
services:
  api:
    build: .
    command: yarn dev
    restart: always
    depends_on:
      - redis
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/usr/crawler
    networks:
      - backend
  redis:
    image: redis:6.0.1-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend   
networks:
  backend:
    driver: bridge